export interface InvestmentProps {
    id: number,
    image: string,
    name: string,
    type: number,
    address: string,
    description: string,
    collected: string,
    reserved: string,
    objective: string,
    maxTarget: string,
    rentability: string,
    projectedPayments: string,
    modality: string,
    participation: string,
    minimalInvestment: string,
    oportunity: string,
    sectors: string,
    society: string,
    maturity: string,
    indicator: string,
    documents: string
}

export const investmentsList = [
    {
        id: 1,
        image: require('../assets/images/restaurant.jpeg'),
        name: 'Empresa 1',
        type: 0,
        address: 'Recife, PE',
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
        collected: '2',
        reserved: '0',
        objective: '23MM',
        maxTarget: '50000000',
        rentability: '31.91%',
        projectedPayments: 'Ao final',
        modality: 'Equity',
        participation: '0.1%',
        minimalInvestment: '1.0',
        oportunity: 'Expansão de operação',
        sectors: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s,',
        society: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
        maturity: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC',
        indicator: 'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form',
        documents: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC',
    },
    {
        id: 2,
        image: require('../assets/images/ti.jpg'),
        name: 'Empresa 2',
        type: 1,
        address: 'Brasília, DF',
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
        collected: '0',
        reserved: '0',
        objective: '90MM',
        maxTarget: '50000000',
        rentability: '31.91%',
        projectedPayments: 'Ao final',
        modality: 'Equity',
        participation: '0.1%',
        minimalInvestment: '1.0',
        oportunity: 'Expansão de operação',
        sectors: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s,',
        society: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
        maturity: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC',
        documents: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC',
        indicator: 'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form'
    },
    {
        id: 3,
        image: require('../assets/images/vestuario.jpg'),
        name: 'Empresa 3',
        type: 2,
        address: 'São Paulo, SP',
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
        collected: '0',
        reserved: '0',
        objective: '57MM',
        maxTarget: '50000000',
        rentability: '31.91%',
        projectedPayments: 'Ao final',
        modality: 'Equity',
        participation: '0.1%',
        minimalInvestment: '1.0',
        oportunity: 'Expansão de operação',
        sectors: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s,',
        society: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
        maturity: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC',
        documents: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC',
        indicator: 'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form'
    },
    {
        id: 4,
        image: require('../assets/images/vestuario.jpg'),
        name: 'Empresa 4',
        type: 2,
        address: 'Rio de Janeiro, RJ',
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
        collected: '0',
        reserved: '0',
        objective: '2MM',
        maxTarget: '50000000',
        rentability: '31.91%',
        projectedPayments: 'Ao final',
        modality: 'Equity',
        participation: '0.1%',
        minimalInvestment: '1.0',
        oportunity: 'Expansão de operação',
        sectors: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s,',
        society: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
        maturity: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC',
        documents: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC',
        indicator: 'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form'
    },
    {
        id: 5,
        image: require('../assets/images/restaurant.jpeg'),
        name: 'Empresa 5',
        type: 0,
        address: 'Campinas, SP',
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
        collected: '0',
        reserved: '0',
        objective: '30MM',
        maxTarget: '50000000',
        rentability: '31.91%',
        projectedPayments: 'Ao final',
        modality: 'Equity',
        participation: '0.1%',
        minimalInvestment: '1.0',
        oportunity: 'Expansão de operação',
        sectors: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s,',
        society: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
        maturity: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC',
        documents: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC',
        indicator: 'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form'
    },
    {
        id: 6,
        image: require('../assets/images/ti.jpg'),
        name: 'Empresa 6',
        type: 1,
        address: 'Recife, PE',
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
        collected: '0',
        reserved: '0',
        objective: '75MM',
        maxTarget: '50000000',
        rentability: '31.91%',
        projectedPayments: 'Ao final',
        modality: 'Equity',
        participation: '0.1%',
        minimalInvestment: '1.0',
        oportunity: 'Expansão de operação',
        sectors: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s,',
        society: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
        maturity: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC',
        documents: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC',
        indicator: 'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form'
    },
    {
        id: 7,
        image: require('../assets/images/restaurant.jpeg'),
        name: 'Empresa 1',
        type: 0,
        address: 'Recife, PE',
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
        collected: '2',
        reserved: '0',
        objective: '23MM',
        maxTarget: '50000000',
        rentability: '31.91%',
        projectedPayments: 'Ao final',
        modality: 'Equity',
        participation: '0.1%',
        minimalInvestment: '1.0',
        oportunity: 'Expansão de operação',
        sectors: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s,',
        society: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
        maturity: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC',
        documents: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC',
        indicator: 'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form'
    },
    {
        id: 8,
        image: require('../assets/images/ti.jpg'),
        name: 'Empresa 2',
        type: 1,
        address: 'Brasília, DF',
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
        collected: '0',
        reserved: '0',
        objective: '90MM',
        maxTarget: '50000000',
        rentability: '31.91%',
        projectedPayments: 'Ao final',
        modality: 'Equity',
        participation: '0.1%',
        minimalInvestment: '1.0',
        oportunity: 'Expansão de operação',
        sectors: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s,',
        society: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
        maturity: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC',
        documents: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC',
        indicator: 'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form'
    },
    {
        id: 9,
        image: require('../assets/images/vestuario.jpg'),
        name: 'Empresa 3',
        type: 2,
        address: 'São Paulo, SP',
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
        collected: '0',
        reserved: '0',
        objective: '57MM',
        maxTarget: '50000000',
        rentability: '31.91%',
        projectedPayments: 'Ao final',
        modality: 'Equity',
        participation: '0.1%',
        minimalInvestment: '1.0',
        oportunity: 'Expansão de operação',
        sectors: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s,',
        society: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
        maturity: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC',
        documents: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC',
        indicator: 'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form'
    },
    {
        id: 10,
        image: require('../assets/images/vestuario.jpg'),
        name: 'Empresa 4',
        type: 2,
        address: 'Rio de Janeiro, RJ',
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
        collected: '0',
        reserved: '0',
        objective: '2MM',
        maxTarget: '50000000',
        rentability: '31.91%',
        projectedPayments: 'Ao final',
        modality: 'Equity',
        participation: '0.1%',
        minimalInvestment: '1.0',
        oportunity: 'Expansão de operação',
        sectors: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s,',
        society: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
        maturity: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC',
        documents: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC',
        indicator: 'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form'
    },
    {
        id: 11,
        image: require('../assets/images/restaurant.jpeg'),
        name: 'Empresa 5',
        type: 0,
        address: 'Campinas, SP',
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
        collected: '0',
        reserved: '0',
        objective: '30MM',
        maxTarget: '50000000',
        rentability: '31.91%',
        projectedPayments: 'Ao final',
        modality: 'Equity',
        participation: '0.1%',
        minimalInvestment: '1.0',
        oportunity: 'Expansão de operação',
        sectors: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s,',
        society: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
        maturity: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC',
        documents: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC',
        indicator: 'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form'
    },
    {
        id: 12,
        image: require('../assets/images/ti.jpg'),
        name: 'Empresa 6',
        type: 1,
        address: 'Recife, PE',
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
        collected: '0',
        reserved: '0',
        objective: '75MM',
        maxTarget: '50000000',
        rentability: '31.91%',
        projectedPayments: 'Ao final',
        modality: 'Equity',
        participation: '0.1%',
        minimalInvestment: '1.0',
        oportunity: 'Expansão de operação',
        sectors: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s,',
        society: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
        maturity: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC',
        documents: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC',
        indicator: 'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form'
    },
    {
        id: 13,
        image: require('../assets/images/restaurant.jpeg'),
        name: 'Empresa 1',
        type: 0,
        address: 'Recife, PE',
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
        collected: '2',
        reserved: '0',
        objective: '23MM',
        maxTarget: '50000000',
        rentability: '31.91%',
        projectedPayments: 'Ao final',
        modality: 'Equity',
        participation: '0.1%',
        minimalInvestment: '1.0',
        oportunity: 'Expansão de operação',
        sectors: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s,',
        society: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
        maturity: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC',
        documents: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC',
        indicator: 'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form'
    },
    {
        id: 14,
        image: require('../assets/images/ti.jpg'),
        name: 'Empresa 2',
        type: 1,
        address: 'Brasília, DF',
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
        collected: '0',
        reserved: '0',
        objective: '90MM',
        maxTarget: '50000000',
        rentability: '31.91%',
        projectedPayments: 'Ao final',
        modality: 'Equity',
        participation: '0.1%',
        minimalInvestment: '1.0',
        oportunity: 'Expansão de operação',
        sectors: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s,',
        society: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
        maturity: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC',
        documents: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC',
        indicator: 'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form'
    },
    {
        id: 15,
        image: require('../assets/images/vestuario.jpg'),
        name: 'Empresa 3',
        type: 2,
        address: 'São Paulo, SP',
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
        collected: '0',
        reserved: '0',
        objective: '57MM',
        maxTarget: '50000000',
        rentability: '31.91%',
        projectedPayments: 'Ao final',
        modality: 'Equity',
        participation: '0.1%',
        minimalInvestment: '1.0',
        oportunity: 'Expansão de operação',
        sectors: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s,',
        society: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
        maturity: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC',
        documents: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC',
        indicator: 'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form'
    },
    {
        id: 16,
        image: require('../assets/images/vestuario.jpg'),
        name: 'Empresa 4',
        type: 2,
        address: 'Rio de Janeiro, RJ',
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
        collected: '0',
        reserved: '0',
        objective: '2MM',
        maxTarget: '50000000',
        rentability: '31.91%',
        projectedPayments: 'Ao final',
        modality: 'Equity',
        participation: '0.1%',
        minimalInvestment: '1.0',
        oportunity: 'Expansão de operação',
        sectors: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s,',
        society: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
        maturity: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC',
        documents: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC',
        indicator: 'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form'
    },
    {
        id: 17,
        image: require('../assets/images/restaurant.jpeg'),
        name: 'Empresa 5',
        type: 0,
        address: 'Campinas, SP',
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
        collected: '0',
        reserved: '0',
        objective: '30MM',
        maxTarget: '50000000',
        rentability: '31.91%',
        projectedPayments: 'Ao final',
        modality: 'Equity',
        participation: '0.1%',
        minimalInvestment: '1.0',
        oportunity: 'Expansão de operação',
        sectors: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s,',
        society: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
        maturity: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC',
        documents: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC',
        indicator: 'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form'
    },
    {
        id: 18,
        image: require('../assets/images/ti.jpg'),
        name: 'Empresa 6',
        type: 1,
        address: 'Recife, PE',
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
        collected: '0',
        reserved: '0',
        objective: '75MM',
        maxTarget: '50000000',
        rentability: '31.91%',
        projectedPayments: 'Ao final',
        modality: 'Equity',
        participation: '0.1%',
        minimalInvestment: '1.0',
        oportunity: 'Expansão de operação',
        sectors: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s,',
        society: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
        maturity: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC',
        documents: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC',
        indicator: 'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form'
    },
    {
        id: 19,
        image: require('../assets/images/restaurant.jpeg'),
        name: 'Empresa 1',
        type: 0,
        address: 'Recife, PE',
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
        collected: '2',
        reserved: '0',
        objective: '23MM',
        maxTarget: '50000000',
        rentability: '31.91%',
        projectedPayments: 'Ao final',
        modality: 'Equity',
        participation: '0.1%',
        minimalInvestment: '1.0',
        oportunity: 'Expansão de operação',
        sectors: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s,',
        society: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
        maturity: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC',
        documents: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC',
        indicator: 'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form'
    },
    {
        id: 20,
        image: require('../assets/images/ti.jpg'),
        name: 'Empresa 2',
        type: 1,
        address: 'Brasília, DF',
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
        collected: '0',
        reserved: '0',
        objective: '90MM',
        maxTarget: '50000000',
        rentability: '31.91%',
        projectedPayments: 'Ao final',
        modality: 'Equity',
        participation: '0.1%',
        minimalInvestment: '1.0',
        oportunity: 'Expansão de operação',
        sectors: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s,',
        society: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
        maturity: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC',
        documents: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC',
        indicator: 'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form'
    },
    {
        id: 21,
        image: require('../assets/images/vestuario.jpg'),
        name: 'Empresa 3',
        type: 2,
        address: 'São Paulo, SP',
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
        collected: '0',
        reserved: '0',
        objective: '57MM',
        maxTarget: '50000000',
        rentability: '31.91%',
        projectedPayments: 'Ao final',
        modality: 'Equity',
        participation: '0.1%',
        minimalInvestment: '1.0',
        oportunity: 'Expansão de operação',
        sectors: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s,',
        society: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
        maturity: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC',
        documents: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC',
        indicator: 'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form'
    },
    {
        id: 22,
        image: require('../assets/images/vestuario.jpg'),
        name: 'Empresa 4',
        type: 2,
        address: 'Rio de Janeiro, RJ',
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
        collected: '0',
        reserved: '0',
        objective: '2MM',
        maxTarget: '50000000',
        rentability: '31.91%',
        projectedPayments: 'Ao final',
        modality: 'Equity',
        participation: '0.1%',
        minimalInvestment: '1.0',
        oportunity: 'Expansão de operação',
        sectors: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s,',
        society: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
        maturity: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC',
        documents: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC',
        indicator: 'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form'
    },
    {
        id: 23,
        image: require('../assets/images/restaurant.jpeg'),
        name: 'Empresa 5',
        type: 0,
        address: 'Campinas, SP',
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
        collected: '0',
        reserved: '0',
        objective: '30MM',
        maxTarget: '50000000',
        rentability: '31.91%',
        projectedPayments: 'Ao final',
        modality: 'Equity',
        participation: '0.1%',
        minimalInvestment: '1.0',
        oportunity: 'Expansão de operação',
        sectors: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s,',
        society: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
        maturity: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC',
        documents: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC',
        indicator: 'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form'
    },
    {
        id: 24,
        image: require('../assets/images/ti.jpg'),
        name: 'Empresa 6',
        type: 1,
        address: 'Recife, PE',
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
        collected: '0',
        reserved: '0',
        objective: '75MM',
        maxTarget: '50000000',
        rentability: '31.91%',
        projectedPayments: 'Ao final',
        modality: 'Equity',
        participation: '0.1%',
        minimalInvestment: '1.0',
        oportunity: 'Expansão de operação',
        sectors: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s,',
        society: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
        maturity: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC',
        documents: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC',
        indicator: 'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form'
    },
    {
        id: 25,
        image: require('../assets/images/restaurant.jpeg'),
        name: 'Empresa 1',
        type: 0,
        address: 'Recife, PE',
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
        collected: '2',
        reserved: '0',
        objective: '23MM',
        maxTarget: '50000000',
        rentability: '31.91%',
        projectedPayments: 'Ao final',
        modality: 'Equity',
        participation: '0.1%',
        minimalInvestment: '1.0',
        oportunity: 'Expansão de operação',
        sectors: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s,',
        society: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
        maturity: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC',
        documents: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC',
        indicator: 'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form'
    },
    {
        id: 26,
        image: require('../assets/images/ti.jpg'),
        name: 'Empresa 2',
        type: 1,
        address: 'Brasília, DF',
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
        collected: '0',
        reserved: '0',
        objective: '90MM',
        maxTarget: '50000000',
        rentability: '31.91%',
        projectedPayments: 'Ao final',
        modality: 'Equity',
        participation: '0.1%',
        minimalInvestment: '1.0',
        oportunity: 'Expansão de operação',
        sectors: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s,',
        society: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
        maturity: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC',
        documents: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC',
        indicator: 'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form'
    },
    {
        id: 27,
        image: require('../assets/images/vestuario.jpg'),
        name: 'Empresa 3',
        type: 2,
        address: 'São Paulo, SP',
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
        collected: '0',
        reserved: '0',
        objective: '57MM',
        maxTarget: '50000000',
        rentability: '31.91%',
        projectedPayments: 'Ao final',
        modality: 'Equity',
        participation: '0.1%',
        minimalInvestment: '1.0',
        oportunity: 'Expansão de operação',
        sectors: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s,',
        society: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
        maturity: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC',
        documents: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC',
        indicator: 'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form'
    },
    {
        id: 28,
        image: require('../assets/images/vestuario.jpg'),
        name: 'Empresa 4',
        type: 2,
        address: 'Rio de Janeiro, RJ',
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
        collected: '0',
        reserved: '0',
        objective: '2MM',
        maxTarget: '50000000',
        rentability: '31.91%',
        projectedPayments: 'Ao final',
        modality: 'Equity',
        participation: '0.1%',
        minimalInvestment: '1.0',
        oportunity: 'Expansão de operação',
        sectors: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s,',
        society: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
        maturity: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC',
        documents: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC',
        indicator: 'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form'
    },
    {
        id: 29,
        image: require('../assets/images/restaurant.jpeg'),
        name: 'Empresa 5',
        type: 0,
        address: 'Campinas, SP',
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
        collected: '0',
        reserved: '0',
        objective: '30MM',
        maxTarget: '50000000',
        rentability: '31.91%',
        projectedPayments: 'Ao final',
        modality: 'Equity',
        participation: '0.1%',
        minimalInvestment: '1.0',
        oportunity: 'Expansão de operação',
        sectors: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s,',
        society: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
        maturity: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC',
        documents: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC',
        indicator: 'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form'
    },
    {
        id: 30,
        image: require('../assets/images/ti.jpg'),
        name: 'Empresa 6',
        type: 1,
        address: 'Recife, PE',
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
        collected: '0',
        reserved: '0',
        objective: '75MM',
        maxTarget: '50000000',
        rentability: '31.91%',
        projectedPayments: 'Ao final',
        modality: 'Equity',
        participation: '0.1%',
        minimalInvestment: '1.0',
        oportunity: 'Expansão de operação',
        sectors: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s,',
        society: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
        maturity: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC',
        documents: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC',
        indicator: 'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form'
    },
    {
        id: 31,
        image: require('../assets/images/restaurant.jpeg'),
        name: 'Empresa 1',
        type: 0,
        address: 'Recife, PE',
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
        collected: '2',
        reserved: '0',
        objective: '23MM',
        maxTarget: '50000000',
        rentability: '31.91%',
        projectedPayments: 'Ao final',
        modality: 'Equity',
        participation: '0.1%',
        minimalInvestment: '1.0',
        oportunity: 'Expansão de operação',
        sectors: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s,',
        society: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
        maturity: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC',
        documents: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC',
        indicator: 'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form'
    },
    {
        id: 32,
        image: require('../assets/images/ti.jpg'),
        name: 'Empresa 2',
        type: 1,
        address: 'Brasília, DF',
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
        collected: '0',
        reserved: '0',
        objective: '90MM',
        maxTarget: '50000000',
        rentability: '31.91%',
        projectedPayments: 'Ao final',
        modality: 'Equity',
        participation: '0.1%',
        minimalInvestment: '1.0',
        oportunity: 'Expansão de operação',
        sectors: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s,',
        society: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
        maturity: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC',
        documents: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC',
        indicator: 'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form'
    },
    {
        id: 33,
        image: require('../assets/images/vestuario.jpg'),
        name: 'Empresa 3',
        type: 2,
        address: 'São Paulo, SP',
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
        collected: '0',
        reserved: '0',
        objective: '57MM',
        maxTarget: '50000000',
        rentability: '31.91%',
        projectedPayments: 'Ao final',
        modality: 'Equity',
        participation: '0.1%',
        minimalInvestment: '1.0',
        oportunity: 'Expansão de operação',
        sectors: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s,',
        society: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
        maturity: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC',
        documents: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC',
        indicator: 'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form'
    },
    {
        id: 34,
        image: require('../assets/images/vestuario.jpg'),
        name: 'Empresa 4',
        type: 2,
        address: 'Rio de Janeiro, RJ',
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
        collected: '0',
        reserved: '0',
        objective: '2MM',
        maxTarget: '50000000',
        rentability: '31.91%',
        projectedPayments: 'Ao final',
        modality: 'Equity',
        participation: '0.1%',
        minimalInvestment: '1.0',
        oportunity: 'Expansão de operação',
        sectors: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s,',
        society: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
        maturity: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC',
        documents: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC',
        indicator: 'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form'
    },
    {
        id: 35,
        image: require('../assets/images/restaurant.jpeg'),
        name: 'Empresa 5',
        type: 0,
        address: 'Campinas, SP',
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
        collected: '0',
        reserved: '0',
        objective: '30MM',
        maxTarget: '50000000',
        rentability: '31.91%',
        projectedPayments: 'Ao final',
        modality: 'Equity',
        participation: '0.1%',
        minimalInvestment: '1.0',
        oportunity: 'Expansão de operação',
        sectors: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s,',
        society: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
        maturity: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC',
        documents: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC',
        indicator: 'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form'
    },
    {
        id: 36,
        image: require('../assets/images/ti.jpg'),
        name: 'Empresa 6',
        type: 1,
        address: 'Recife, PE',
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
        collected: '0',
        reserved: '0',
        objective: '75MM',
        maxTarget: '50000000',
        rentability: '31.91%',
        projectedPayments: 'Ao final',
        modality: 'Equity',
        participation: '0.1%',
        minimalInvestment: '1.0',
        oportunity: 'Expansão de operação',
        sectors: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s,',
        society: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
        maturity: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC',
        documents: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC',
        indicator: 'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form'
    },
    {
        id: 37,
        image: require('../assets/images/restaurant.jpeg'),
        name: 'Empresa 1',
        type: 0,
        address: 'Recife, PE',
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
        collected: '2',
        reserved: '0',
        objective: '23MM',
        maxTarget: '50000000',
        rentability: '31.91%',
        projectedPayments: 'Ao final',
        modality: 'Equity',
        participation: '0.1%',
        minimalInvestment: '1.0',
        oportunity: 'Expansão de operação',
        sectors: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s,',
        society: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
        maturity: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC',
        documents: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC',
        indicator: 'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form'
    },
    {
        id: 38,
        image: require('../assets/images/ti.jpg'),
        name: 'Empresa 2',
        type: 1,
        address: 'Brasília, DF',
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
        collected: '0',
        reserved: '0',
        objective: '90MM',
        maxTarget: '50000000',
        rentability: '31.91%',
        projectedPayments: 'Ao final',
        modality: 'Equity',
        participation: '0.1%',
        minimalInvestment: '1.0',
        oportunity: 'Expansão de operação',
        sectors: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s,',
        society: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
        maturity: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC',
        documents: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC',
        indicator: 'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form'
    },
    {
        id: 39,
        image: require('../assets/images/vestuario.jpg'),
        name: 'Empresa 3',
        type: 2,
        address: 'São Paulo, SP',
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
        collected: '0',
        reserved: '0',
        objective: '57MM',
        maxTarget: '50000000',
        rentability: '31.91%',
        projectedPayments: 'Ao final',
        modality: 'Equity',
        participation: '0.1%',
        minimalInvestment: '1.0',
        oportunity: 'Expansão de operação',
        sectors: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s,',
        society: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
        maturity: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC',
        documents: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC',
        indicator: 'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form'
    },
    {
        id: 40,
        image: require('../assets/images/vestuario.jpg'),
        name: 'Empresa 4',
        type: 2,
        address: 'Rio de Janeiro, RJ',
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
        collected: '0',
        reserved: '0',
        objective: '2MM',
        maxTarget: '50000000',
        rentability: '31.91%',
        projectedPayments: 'Ao final',
        modality: 'Equity',
        participation: '0.1%',
        minimalInvestment: '1.0',
        oportunity: 'Expansão de operação',
        sectors: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s,',
        society: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
        maturity: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC',
        documents: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC',
        indicator: 'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form'
    },
    {
        id: 41,
        image: require('../assets/images/restaurant.jpeg'),
        name: 'Empresa 5',
        type: 0,
        address: 'Campinas, SP',
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
        collected: '0',
        reserved: '0',
        objective: '30MM',
        maxTarget: '50000000',
        rentability: '31.91%',
        projectedPayments: 'Ao final',
        modality: 'Equity',
        participation: '0.1%',
        minimalInvestment: '1.0',
        oportunity: 'Expansão de operação',
        sectors: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s,',
        society: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
        maturity: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC',
        documents: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC',
        indicator: 'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form'
    },
    {
        id: 42,
        image: require('../assets/images/ti.jpg'),
        name: 'Empresa 6',
        type: 1,
        address: 'Recife, PE',
        description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
        collected: '0',
        reserved: '0',
        objective: '75MM',
        maxTarget: '50000000',
        rentability: '31.91%',
        projectedPayments: 'Ao final',
        modality: 'Equity',
        participation: '0.1%',
        minimalInvestment: '1.0',
        oportunity: 'Expansão de operação',
        sectors: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s,',
        society: 'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.',
        maturity: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC',
        documents: 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC',
        indicator: 'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form'
    },
];